---
title: "Introduction"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


#1. Setup configuration


```{r}
devtools::load_all()
setupWorkspace(filePath="/home/ubuntu/TFG/R/distR/configuration.txt")
```



#2. execute lines of code 
```{r}
a<-c(1,2,3)
b<-c(2,3,4)
objects<-list(a=a,b=b)
token<-executeLines("c<-a+b;c(c*2,1)",objects)
c<-getResults(token)
identical(c,c((a+b)*2,1))
```
#2. execute lines of code with error
```{r}
a<-c(1,2,3)
b<-c(2,3,4)
objects<-list(a=a,b=b)
token<-executeLines("c<-a+b,c*2",objects)
c<-getResults(token)
```



```{r}
a<-c(1,2,3)
b<-c(2,3,4)
objects<-list(a=a,b=b)
token<-executeLines("f<-function( a,b){PCA(a+b)};f(a,b);",objects)

```

#3. get results
```{r}
c<-getResults(token)
c
```

#4. distributed apply



```{r}
c<-0.2
t<-function(data,c1,c2){return(mean(data)+c1+c2)}
dat<-matrix(c(1:20),ncol=2)
token<-distApply(dat,FUN=t,MARGIN=1,c1=c,c2=c+1)



```

```{r}
df<-getResults(token)
df
```

#5. distributed tapply

```{r}
data_set <- data.frame(
  price = round(rnorm(25, sd = 10, mean = 30)),
  type = sample(1:4, size = 25, replace = TRUE),
  store = sample(paste("Store", 1:4),
                 size = 25, replace = TRUE)
)
price <- data_set$price
store <- data_set$store
type <- factor(data_set$type,
               labels = c("toy", "food", "electronics", "drinks"))

tapply(price,type,mean)
```

```{r}
token<-distTApply(price,INDEX=type,FUN=mean,simplify=FALSE)
df1<-getResults(token)
df1
```
#6. distributed Lapply

```{r}
c<-0.3
l<-list(1,2,3,1,2,3,7,8,1,3,6,9)
t<-function(data,c1,c2){return(data+c1+c2)}
token<-distLApply(l,FUN=t,c1=c,c2=c+1)

```

```{r}
df1<-getResults(token)
df1
```
#7. distributed sapply

```{r}
c<-0.3
l<-list(1,2,3,1,2,3,7,8,1,3,6,9)
t<-function(data,c1,c2){return(data+c1+c2)}
token<-distSApply(l,FUN=t,c1=c,c2=c+1,simplify = TRUE)

```

```{r}
df1<-getResults(token)
df1
```
